name: Use gcloud SDK

on:
  push:
    branches:
      - master

jobs:
  gcloud:
    name: Get gcloud info
    uses: google-github-actions/setup-gcloud@master
    with:
      project_id: ${{ secrets.GCP_PROJECT_ID }}
      service_account_key: ${{ secrets.GCP_SA_KEY }}
      export_default_credentials: true
    run: gcloud info
