# This is a basic workflow to help you get started with Actions

name: CI

on:
  pull_request:
    branches-ignore: [ master ]

jobs:
  deploy:
    name: Build and deploy
    steps:
      - name: Echo command
      - run: echo "hello"