name: Use gcloud SDK

on:
  push:
    branches:
      - master

jobs:
  gcloud:
    name: Get gcloud info
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Get info
        run: gcloud info
