- name: Use gcloud SDK
  uses: google-github-actions/setup-gcloud@master
  with:
    project_id: ${{ secrets.GCP_PROJECT_ID }}
    service_account_key: ${{ secrets.GCP_SA_KEY }}
    export_default_credentials: true

- on:
  push:
    branches:
      - master

- name: Deploy Project
  run: gcloud info
