name: CI

on:
  pull_request:
    type: [ open ]
    branches: [ master ]

jobs:
  deploy:
    name: Build and deploy
    runs-on: ubuntu-20.04
    steps:
      - uses: FranzDiebold/github-env-vars-action@v1.0.0
      - uses: actions/checkout@v1
