name: CI

on:
  pull_request:
    type: [ open ]
    branches: [ master ]

jobs:
  deploy:
    name: Build and deploy
    runs-on: ubuntu-20.04
    steps:
      - name: Echo Command
        run: echo "hello"
